### ISSUE TITLE
New repository structure

### ISSUE THREAD

**Issue by cristirusu** [crowdfavorite/wp-capsule-server#23]
The latest development for the Client, Server and the Capsule UI was made on the develop branch.
The server and the client specific code was updated to our latest standards. However updating the Capsule UI code is more difficult as we dropped the submodule approach and now the same code is in 3 repos.
The suggested approach for continuing the development is to use git subrepo https://github.com/ingydotnet/git-subrepo/

This approach is tested now in the `restructure` branch on server and client. The ui directory is added as a subrepo.
To keep the commit history clean, separate the commits made for the server/client code from the commits mades for the code in the ui directory.

The workflow for updating the ui code while working in the server/client project would be:

-  from the current working branch of the main project, create a new temporary branch `git checkout -b temp-branch`
-  commit the files that were updated in the ui directory
- push the commit to the Capsule UI repo, in a new branch: `git subrepo push ui -b some-remote-branch-name`
- open a pull request on the Capsule UI repo, merge the code in the current dev branch (develop)
- switch back to the working branch `git checkout development-branch`
- update the ui subrepo `git subrepo pull ui -b develop` (in case of errors run `git subrepo clean ui`)

**Comment by al-esc** [comment]
Closing because we have migrated to git subtree
