### ISSUE TITLE
Adding Capsule Server to local Capsule failing

### ISSUE THREAD

**Issue by phillcoxon** [crowdfavorite/wp-capsule-server#9]
Similar to a previous isssue, I'm getting an "Error: Enspiral Capsule - Server theme not active" error trying to connect to a Capsule Server in a local Capsule install.    

I'm running WP 3.7.1 both locally for Capsule (using Desktop Server for Mac)  and online for Capsule Server. 

I can ping the Capsule Server install just fine locally. 

Any suggestions for what to try?  Thank you!

**Comment by al-esc** [comment]
Closed because it's stale
